### ISSUE TITLE
libusb error when selecting alignment ... and laser turns off / PeachyPrinter_amd64-0.6.614.exe

### ISSUE THREAD

**Issue by perfessor101** [PeachyPrinter/peachyprintertools#5]
E57472FF.cfg
{
  "calibration": {
    "flip_x_axis": true, 
    "flip_y_axis": false, 
    "height": 40.0, 
    "lower_points": [
      [
        [
          0.0, 
          1.0
        ], 
        [
          -40.0, 
          40.0
        ]
      ], 
      [
        [
          1.0, 
          0.0
        ], 
        [
          40.0, 
          -40.0
        ]
      ], 
      [
        [
          0.0, 
          0.0
        ], 
        [
          -40.0, 
          -40.0
        ]
      ], 
      [
        [
          1.0, 
          1.0
        ], 
        [
          40.0, 
          40.0
        ]
      ]
    ], 
    "max_deflection": 0.95, 
    "print_area_x": 80.0, 
    "print_area_y": 80.0, 
    "print_area_z": 80.0, 
    "swap_axis": false, 
    "upper_points": [
      [
        [
          0.0, 
          1.0
        ], 
        [
          -30.0, 
          30.0
        ]
      ], 
      [
        [
          1.0, 
          0.0
        ], 
        [
          30.0, 
          -30.0
        ]
      ], 
      [
        [
          0.0, 
          0.0
        ], 
        [
          -30.0, 
          -30.0
        ]
      ], 
      [
        [
          1.0, 
          1.0
        ], 
        [
          30.0, 
          30.0
        ]
      ]
    ]
  }, 
  "circut": {
    "calibration_queue_length": 50, 
    "data_rate": 2000, 
    "hardware_revision": "hwrev 3456", 
    "print_queue_length": 500, 
    "serial_number": "E57472FF", 
    "software_revision": ""
  }, 
  "cure_rate": {
    "base_height": 3.0, 
    "draw_speed": 80.0, 
    "finish_speed": 200.0, 
    "move_speed": 300.0, 
    "override_laser_power": true, 
    "override_laser_power_amount": 0.65, 
    "start_speed": 50.0, 
    "total_height": 23.0, 
    "use_draw_speed": true
  }, 
  "dripper": {
    "dripper_type": "microcontroller", 
    "drips_per_mm": 280.0, 
    "emulated_drips_per_second": 2.75, 
    "max_lead_distance_mm": 1.0, 
    "photo_zaxis_delay": 3.0
  }, 
  "email": {
    "email_regex": "\\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,4}\\b", 
    "host": "some.smtp.server", 
    "on": false, 
    "password": "", 
    "port": 25, 
    "recipient": "recipientemail@email.com", 
    "sender": "senderemail@email.com", 
    "username": ""
  }, 
  "name": "E57472FF", 
  "options": {
    "laser_thickness_mm": 0.5, 
    "overlap_amount": 1.0, 
    "post_fire_delay": 0, 
    "pre_layer_delay": 0.0, 
    "print_queue_delay": 0.0, 
    "scaling_factor": 1.0, 
    "shuffle_layers_amount": 1.0, 
    "slew_delay": 15, 
    "sublayer_height_mm": 0.01, 
    "use_overlap": false, 
    "use_shufflelayers": false, 
    "use_sublayers": false, 
    "wait_after_move_milliseconds": 20, 
    "write_wav_files": false, 
    "write_wav_files_folder": "tmp"
  }, 
  "serial": {
    "layer_ended": "E", 
    "layer_started": "S", 
    "off_command": "8", 
    "on": false, 
    "on_command": "7", 
    "port": "COM2", 
    "print_ended": "Z"
  }
}
peachyprinter.log empty

**Comment by jtownley** [comment]
Internal ref #112056161
https://youtu.be/0K5B-RsZh20

This is a timeout error and could be a number of things:  bad cable, connection, port, board, slow or overloaded computer. It cannot be reproduced on this end without the purposeful, introduction of a poor connection in the USB line.

Note: This class of error needs a better error that can be surfaced to the user containing context. Created a feature request for this.

**Comment by perfessor101** [comment]
Thank you
Helpful errors speed up the self diagnosis

I'm looking into other systems to try the software on

But most of my other Windows systems are 32 bit ... Either XP or 7

I can setup a Linux system pretty easily

Thanks for your time
Bobby

**Comment by jtownley** [comment]
If you shoot me your email address at software@peachyprinter.com, I can get you hooked up with the 32 and 64 bit windows or mac software pre-releases versions.
